"""AI-first analytics planner powered by local Qwen through Ollama.

Qwen is responsible for:
- understanding English, Myanmar, and mixed-language questions;
- deciding whether clarification is required;
- selecting an analytical intent, metric, dimension, filters, and tools;
- recommending a visualization.

Qwen is not responsible for numerical calculations. All calculations remain in
validated deterministic tools such as Pandas-based executors.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import Any, Literal

import pandas as pd

def _enum_or_string_value(
    value: object,
    default: str = "unknown",
) -> str:
    """Return a stable string from either an enum or a string."""

    if value is None:
        return default

    enum_value = getattr(
        value,
        "value",
        value,
    )

    text = str(enum_value).strip()

    return text or default

from pydantic import BaseModel, Field, ValidationError, field_validator, model_validator

from app.agents.question_parser import parse_question

try:
    import ollama
except ImportError:  # pragma: no cover - exercised only without optional package
    ollama = None


DEFAULT_MODEL = os.getenv("OLLAMA_MODEL", "qwen3:4b")
DEFAULT_TIMEOUT_SECONDS = int(os.getenv("OLLAMA_TIMEOUT_SECONDS", "180"))

SUPPORTED_TOOLS = {
    "inspect_schema",
    "profile_dataset",
    "apply_filters",
    "calculate_summary",
    "calculate_ranking",
    "calculate_trend",
    "calculate_distribution",
    "calculate_correlation",
    "analyze_data_quality",
    "validate_pdf_quality",
    "generate_chart",
}


class PlannerFilter(BaseModel):
    """One structured filter generated by the AI planner."""

    column: str = Field(min_length=1)
    operator: Literal[
        "equals",
        "not_equals",
        "greater_than",
        "greater_than_or_equal",
        "less_than",
        "less_than_or_equal",
        "contains",
        "in",
        "between",
    ] = "equals"
    value: Any


class ToolStep(BaseModel):
    """One approved tool call proposed by the planner."""

    tool: str = Field(min_length=1)
    reason: str = Field(min_length=1)

    @field_validator("tool")
    @classmethod
    def validate_tool_name(cls, value: str) -> str:
        normalized = value.strip()
        if normalized not in SUPPORTED_TOOLS:
            raise ValueError(
                f"Unsupported tool '{normalized}'. "
                f"Allowed tools: {sorted(SUPPORTED_TOOLS)}"
            )
        return normalized


class AIAnalysisPlan(BaseModel):
    """Validated structured output returned by the local AI planner."""

    requires_clarification: bool = False
    clarification_question: str | None = None
    language: Literal["en", "my", "mixed", "unknown"] = "unknown"
    intent: Literal[
        "summary",
        "ranking",
        "trend",
        "comparison",
        "distribution",
        "data_quality",
        "correlation",
        "unknown",
    ] = "unknown"
    metric: str | None = None
    dimension: str | None = None
    aggregation: Literal["sum", "mean", "count", "min", "max"] = "sum"
    filters: list[PlannerFilter] = Field(default_factory=list)
    sort_direction: Literal["ascending", "descending"] | None = None
    limit: int | None = Field(default=None, ge=1, le=1000)
    visualization: Literal[
        "kpi",
        "bar",
        "line",
        "histogram",
        "scatter",
        "table",
    ] = "table"
    tool_steps: list[ToolStep] = Field(default_factory=list)
    reasoning_summary: str = Field(
        default=(
            "The local AI planner selected a grounded analytical "
            "operation using the uploaded dataset schema."
        ),
        min_length=1,
    )
    assumptions: list[str] = Field(default_factory=list)
    confidence: float = Field(
        default=0.75,
        ge=0.0,
        le=1.0,
    )

    @model_validator(mode="after")
    def validate_plan_consistency(self) -> "AIAnalysisPlan":
        if self.requires_clarification:
            if not self.clarification_question:
                raise ValueError(
                    "A clarification question is required when "
                    "requires_clarification is true."
                )
            return self

        if self.intent in {"summary", "ranking", "trend", "comparison", "distribution"}:
            if not self.metric:
                raise ValueError(
                    f"Intent '{self.intent}' requires a metric."
                )

        if self.intent in {"ranking", "trend", "comparison"} and not self.dimension:
            raise ValueError(
                f"Intent '{self.intent}' requires a dimension."
            )

        if self.intent == "ranking" and self.sort_direction is None:
            raise ValueError("Ranking requires sort_direction.")

        if not self.tool_steps:
            raise ValueError("A non-clarification plan requires tool_steps.")

        return self


@dataclass
class AIPlannerResult:
    """Planner result plus model and fallback provenance."""

    plan: AIAnalysisPlan
    source: str
    model: str
    fallback_reason: str | None = None
    raw_content: str | None = None

    def metadata(self) -> dict[str, Any]:
        return {
            "source": self.source,
            "model": self.model,
            "fallback_reason": self.fallback_reason,
            "plan": self.plan.model_dump(mode="json"),
        }


def build_dataset_context(
    dataframe: pd.DataFrame,
    *,
    maximum_sample_values: int = 5,
) -> dict[str, Any]:
    """Build compact, privacy-conscious schema context for the local planner."""

    if not isinstance(dataframe, pd.DataFrame):
        raise TypeError("dataframe must be a pandas DataFrame")

    columns: list[dict[str, Any]] = []

    for column in dataframe.columns:
        series = dataframe[column]
        samples = [
            _json_safe(value)
            for value in series.dropna().drop_duplicates().head(
                maximum_sample_values
            ).tolist()
        ]
        columns.append(
            {
                "name": str(column),
                "dtype": str(series.dtype),
                "non_null_count": int(series.notna().sum()),
                "missing_count": int(series.isna().sum()),
                "unique_count": int(series.nunique(dropna=True)),
                "sample_values": samples,
            }
        )

    return {
        "row_count": int(len(dataframe)),
        "column_count": int(len(dataframe.columns)),
        "columns": columns,
        "supported_derived_metrics": {
            "revenue": "quantity * unit_price",
            "profit": "quantity * (unit_price - unit_cost)",
        },
        "approved_tools": sorted(SUPPORTED_TOOLS),
    }


def _json_safe(value: Any) -> Any:
    """Convert Pandas values into JSON-compatible values."""

    if value is None:
        return None

    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass

    if isinstance(value, pd.Timestamp):
        return value.isoformat()

    if hasattr(value, "item"):
        try:
            return value.item()
        except (ValueError, TypeError):
            pass

    return value


SYSTEM_PROMPT = """
You are the primary planning agent for InsightFlow AI, a local bilingual data
analytics application. Convert the user's question and dataset schema into one
validated analysis plan.

You may understand English, Myanmar, and mixed-language requests. Respond only
with JSON matching the supplied schema.

Critical safety rules:
1. Never calculate, estimate, or invent a business value.
2. Never include an analytical result, total, percentage, ranking result, or
   answer to the user's business question.
3. Select only tools listed in approved_tools.
4. Use only columns present in the dataset context, except the supported
   derived metrics revenue and profit.
5. When a request is ambiguous, set requires_clarification=true and ask one
   concise question instead of guessing.
6. Words such as best, performance, weak, strong, successful, and attention
   are ambiguous unless the user states the metric.
7. Do not assume currency, units, date interpretation, or business definitions
   that are not present in the question or schema.
8. Revenue means quantity * unit_price only when those columns are available.
9. Profit means quantity * (unit_price - unit_cost) only when those columns are
   available. This is gross transaction profit, not net profit.
10. reasoning_summary must describe planning logic only and must not expose
    hidden chain-of-thought or contain calculated results.

Planning rules:
- summary: one aggregated value without grouping; visualization=kpi.
- ranking: grouped and ordered result; requires dimension and sort direction;
  visualization=bar.
- trend: time-grouped result; visualization=line.
- comparison: comparison across groups; visualization=bar.
- distribution: spread or frequency; visualization=histogram.
- correlation: numeric relationship; visualization=scatter.
- data_quality: missing values, duplicates, invalid values, or schema issues;
  visualization=table.

For a non-clarification plan, tool_steps should normally include:
- inspect_schema;
- validate_pdf_quality when PDF quality evidence may be relevant;
- apply_filters when filters exist;
- exactly one primary calculation tool appropriate to the intent;
- generate_chart when visualization is not table.
""".strip()


def ollama_is_available() -> bool:
    """Return whether the optional client and local server are available."""

    if ollama is None:
        return False

    try:
        ollama.list()
    except Exception:
        return False

    return True


def _response_content(response: Any) -> str:
    """Read content from dict-based or object-based Ollama clients."""

    if isinstance(response, dict):
        message = response.get("message", {})
        if isinstance(message, dict):
            return str(message.get("content", "") or "").strip()
        return str(getattr(message, "content", "") or "").strip()

    message = getattr(response, "message", None)
    return str(getattr(message, "content", "") or "").strip()


def plan_with_qwen(
    question: str,
    dataframe: pd.DataFrame,
    *,
    model: str = DEFAULT_MODEL,
) -> AIPlannerResult:
    """Create a structured plan with local Qwen and strict validation."""

    if not question or not question.strip():
        raise ValueError("question must not be empty")

    if not ollama_is_available():
        raise RuntimeError("The local Ollama server is unavailable.")

    context = build_dataset_context(dataframe)
    payload = {
        "user_question": question.strip(),
        "dataset_context": context,
    }

    response = ollama.chat(
        model=model,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": json.dumps(
                    payload,
                    ensure_ascii=False,
                    default=str,
                ),
            },
        ],
        format="json",
        options={
            "temperature": 0,
            "seed": 42,
            "top_p": 0.1,
        },
    )

    content = _response_content(response)

    if not content:
        raise RuntimeError("Qwen returned an empty planning response.")

    try:
        plan = AIAnalysisPlan.model_validate_json(content)
    except ValidationError as error:
        raise RuntimeError(
            "Qwen returned a plan that failed Pydantic validation: "
            f"{error}"
        ) from error

    _ground_plan_to_dataframe(plan, dataframe)

    return AIPlannerResult(
        plan=plan,
        source="local_qwen",
        model=model,
        raw_content=content,
    )


def _ground_plan_to_dataframe(
    plan: AIAnalysisPlan,
    dataframe: pd.DataFrame,
) -> None:
    """Reject AI fields that cannot be grounded to the uploaded dataset."""

    if plan.requires_clarification:
        return

    columns = {str(column).casefold() for column in dataframe.columns}
    derived_metrics = {"revenue", "profit"}

    if plan.metric and plan.metric.casefold() not in columns | derived_metrics:
        raise ValueError(
            f"The AI-selected metric '{plan.metric}' is not grounded to "
            "the uploaded dataset."
        )

    if plan.dimension and plan.dimension.casefold() not in columns | {
        "month",
        "quarter",
        "year",
        "date",
    }:
        raise ValueError(
            f"The AI-selected dimension '{plan.dimension}' is not grounded "
            "to the uploaded dataset."
        )

    for condition in plan.filters:
        if condition.column.casefold() not in columns:
            raise ValueError(
                f"The AI-selected filter column '{condition.column}' does "
                "not exist in the uploaded dataset."
            )


def _fallback_plan(question: str) -> AIAnalysisPlan:
    """Convert the existing rule parser output into the AI planner schema."""

    rule_plan = parse_question(question)
    intent = rule_plan.intent.value
    visualization = rule_plan.visualization.value

    tool_map = {
        "summary": "calculate_summary",
        "ranking": "calculate_ranking",
        "trend": "calculate_trend",
        "comparison": "calculate_ranking",
        "distribution": "calculate_distribution",
        "data_quality": "analyze_data_quality",
        "correlation": "calculate_correlation",
    }

    steps = [
        ToolStep(
            tool="inspect_schema",
            reason="Verify dataset fields before deterministic execution.",
        )
    ]

    if rule_plan.filters:
        steps.append(
            ToolStep(
                tool="apply_filters",
                reason="Apply the filters identified in the user question.",
            )
        )

    calculation_tool = tool_map.get(intent)
    if calculation_tool:
        steps.append(
            ToolStep(
                tool=calculation_tool,
                reason="Execute the requested deterministic analysis.",
            )
        )

    if visualization != "table" and calculation_tool:
        steps.append(
            ToolStep(
                tool="generate_chart",
                reason="Visualize the validated analytical result.",
            )
        )

    requires_clarification = (
        intent == "unknown"
        or (
            intent in {"summary", "ranking", "trend", "comparison", "distribution"}
            and rule_plan.metric is None
        )
    )

    return AIAnalysisPlan(
        requires_clarification=requires_clarification,
        clarification_question=(
            "Which metric and comparison would you like to analyze?"
            if requires_clarification
            else None
        ),
        language=getattr(rule_plan.language, "value", rule_plan.language),
        intent=intent,
        metric=rule_plan.metric,
        dimension=rule_plan.dimension,
        aggregation=rule_plan.aggregation,
        filters=[
            PlannerFilter.model_validate(item.model_dump())
            for item in rule_plan.filters
        ],
        sort_direction=(
            rule_plan.sort_direction.value
            if rule_plan.sort_direction is not None
            else None
        ),
        limit=rule_plan.limit,
        visualization=visualization,
        tool_steps=[] if requires_clarification else steps,
        reasoning_summary=(
            "The offline deterministic parser created this fallback plan."
        ),
        assumptions=[],
        confidence=float(rule_plan.confidence),
    )


def create_ai_plan(
    question: str,
    dataframe: pd.DataFrame,
    *,
    model: str = DEFAULT_MODEL,
    allow_rule_fallback: bool = True,
) -> AIPlannerResult:
    """Use Qwen as the primary planner and rules only as offline fallback."""

    try:
        return plan_with_qwen(
            question,
            dataframe,
            model=model,
        )
    except Exception as error:
        if not allow_rule_fallback:
            raise

        return AIPlannerResult(
            plan=_fallback_plan(question),
            source="rule_fallback",
            model=model,
            fallback_reason=str(error),
        )


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Create a Qwen-first analysis plan for a CSV dataset."
    )
    parser.add_argument("csv_path")
    parser.add_argument("question")
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--no-fallback", action="store_true")
    arguments = parser.parse_args()

    frame = pd.read_csv(arguments.csv_path)
    result = create_ai_plan(
        arguments.question,
        frame,
        model=arguments.model,
        allow_rule_fallback=not arguments.no_fallback,
    )
    print(
        json.dumps(
            result.metadata(),
            ensure_ascii=False,
            indent=2,
            default=str,
        )
    )
